name: Update firm list

on:
  schedule:
    # Run once every seven days (Sunday at 00:00 UTC)
    - cron: '0 0 * * 0'
  workflow_dispatch:
    # Allow manual triggering
    inputs: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install requests

      - name: Run update script
        run: python update_csv.py

      - name: Commit changes
        run: |
          git config --local user.name 'github-actions'
          git config --local user.email 'github-actions@github.com'
          if ! git diff --quiet; then
            git add all_firms.csv
            git commit -m 'Update firm status CSV'
          fi

      - name: Push changes
        if: github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}